// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH0mrMdD7eQwE1QIRdFk9nyoTOM6sRaLE',
    appId: '1:720436005385:web:b79856307eb351f56346d8',
    messagingSenderId: '720436005385',
    projectId: 'selvplukk-cbd5f',
    authDomain: 'selvplukk-cbd5f.firebaseapp.com',
    storageBucket: 'selvplukk-cbd5f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb5a2weCo2RfZbOHgoTCzoX4jhqjm6z2c',
    appId: '1:720436005385:android:eb1dd24d2dbe14f66346d8',
    messagingSenderId: '720436005385',
    projectId: 'selvplukk-cbd5f',
    storageBucket: 'selvplukk-cbd5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA8nuKMWbXVNq02FIpKA5t8OMYoM-1ko4',
    appId: '1:720436005385:ios:b3f4de6c4ddf9ecc6346d8',
    messagingSenderId: '720436005385',
    projectId: 'selvplukk-cbd5f',
    storageBucket: 'selvplukk-cbd5f.firebasestorage.app',
    iosBundleId: 'com.splukk.splukk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH0mrMdD7eQwE1QIRdFk9nyoTOM6sRaLE',
    appId: '1:720436005385:web:87842bbe65159c026346d8',
    messagingSenderId: '720436005385',
    projectId: 'selvplukk-cbd5f',
    authDomain: 'selvplukk-cbd5f.firebaseapp.com',
    storageBucket: 'selvplukk-cbd5f.firebasestorage.app',
  );
}
