name: csc_picker
description: A flutter package to display list of Countries, States and Cities depends on Selected, also you can search country, state, and city all around the world.
version: 0.2.7
homepage: https://github.com/altafc22/csc_picker

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter
