const Map<String, Map<String, String>> products = {
  "berries": {
    "strawberry": "Strawberry",
    "raspberry": "Raspberry",
    "blueberry": "Blueberry",
    "blackcurrant": "Blackcurrant",
    "redcurrant": "Redcurrant",
    "gooseberry": "Gooseberry",
    "blackberry": "Blackberry",
    "cultivated_blueberry": "Cultivated blueberry",
  },
  "fruits": {
    "apple": "Apple",
    "pear": "Pear",
    "plum": "Plum",
    "cherry": "Cherry",
    "sweet_cherry": "Sweet cherry",
    "rhubarb": "Rhubarb",
    "grape": "Grape",
  },
  "vegetables": {
    "potato": "Potato",
    "carrot": "Carrot",
    "onion": "Onion",
    "garlic": "Garlic",
    "leek": "Leek",
    "beetroot": "Beetroot",
    "turnip": "Turnip",
    "rutabaga": "Rutabaga",
    "radish": "Radish",
    "lettuce": "Lettuce",
    "spinach": "Spinach",
    "kale": "Kale",
    "white_cabbage": "White cabbage",
    "red_cabbage": "Red cabbage",
    "cauliflower": "Cauliflower",
    "broccoli": "Broccoli",
    "celery": "Celery",
    "celeriac": "Celeriac",
    "sugar_snap_peas": "Sugar snap peas",
    "peas": "Peas",
    "beans": "Beans",
    "cucumber": "Cucumber",
    "zucchini": "Zucchini",
    "pumpkin": "Pumpkin",
    "corn": "Corn",
  },
  "herbs": {
    "parsley": "Parsley",
    "dill": "Dill",
    "chives": "Chives",
    "basil": "Basil",
    "mint": "Mint",
    "thyme": "Thyme",
    "rosemary": "Rosemary",
  },
  "flowers": {
    "sunflower": "Sunflower",
    "dahlia": "Dahlia",
    "tulip": "Tulip",
    "peony": "Peony",
    "summer_flowers": "Summer flowers",
  },
};
